### ISSUE TITLE
Application height exceeds screen height

### ISSUE THREAD

**Issue by pmackenz** [NHERI-SimCenter/MDOF#13]
Running on a MacBook Pro 13", the application is taller than the screen allows for.  This makes it impossible to get to the bottom buttons. The application also appears to have a minimum size that prevents the user from resizing it to a suitable height.
<img width="1280" alt="screen shot 2017-10-12 at 3 06 31 pm" src="https://user-images.githubusercontent.com/15879316/31521616-13acced8-af5f-11e7-87db-5cc9d7271ce1.png">

**Comment by fmckenna** [comment]
fixed
